[package]
name = "imager"
version = "0.1.0"
authors = ["kwe <kwevans.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
photon-rs = "0.2.0"
glob = "0.3.0"
